"""initial_task_persistence

Revision ID: 0001
Revises:
Create Date: 2026-09-15 22:12:01.704768
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    for schema in ("iam", "content", "policy", "workflow", "integration"):
        op.execute(sa.text(f'CREATE SCHEMA IF NOT EXISTS "{schema}"'))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','SUSPENDED')", name=op.f("ck_organization_status_allowed")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_organization_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization")),
        schema="iam",
    )
    op.create_table(
        "user_account",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("normalized_username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("credential_version", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING_FIRST_LOGIN','ACTIVE','DISABLED')",
            name=op.f("ck_user_account_status_allowed"),
        ),
        sa.CheckConstraint(
            "credential_version >= 1", name=op.f("ck_user_account_credential_version_positive")
        ),
        sa.CheckConstraint(
            "failed_login_count >= 0", name=op.f("ck_user_account_failed_login_count_nonnegative")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_user_account_version_positive")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["iam.organization.id"],
            name=op.f("fk_user_account_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_account")),
        sa.UniqueConstraint(
            "normalized_username", name=op.f("uq_user_account_normalized_username")
        ),
        schema="iam",
    )
    op.create_index(
        "ix_user_account_status", "user_account", ["status"], unique=False, schema="iam"
    )
    op.create_table(
        "artifact",
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("origin_upload_id", sa.UUID(), nullable=True),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("artifact_type", sa.String(length=128), nullable=False),
        sa.Column("storage_backend", sa.String(length=32), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.CHAR(length=64), nullable=False),
        sa.Column("declared_media_type", sa.String(length=128), nullable=True),
        sa.Column("detected_media_type", sa.String(length=128), nullable=False),
        sa.Column("schema_id", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("schema_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("data_labels_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("encryption_profile", sa.String(length=64), nullable=False),
        sa.Column("preflight_run_id", sa.UUID(), nullable=True),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("retention_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legal_hold", sa.Boolean(), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("created_by_actor_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purpose <> 'TASK_ATTACHMENT' OR (owner_id IS NOT NULL AND preflight_run_id IS NOT NULL)",
            name=op.f("ck_artifact_task_attachment_requires_owner_and_preflight"),
        ),
        sa.CheckConstraint(
            "schema_digest ~ '^[0-9a-f]{64}$'", name=op.f("ck_artifact_schema_digest_lower_hex")
        ),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_artifact_sha256_lower_hex")),
        sa.CheckConstraint(
            "state IN ('STAGED','QUARANTINED','PREFLIGHTING','AVAILABLE','REJECTED','UNSUPPORTED','SCAN_UNAVAILABLE','DELETING','DELETED')",
            name=op.f("ck_artifact_state_allowed"),
        ),
        sa.CheckConstraint("row_version >= 1", name=op.f("ck_artifact_row_version_positive")),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_artifact_size_bytes_nonnegative")),
        sa.ForeignKeyConstraint(
            ["created_by_actor_id"],
            ["iam.user_account.id"],
            name=op.f("fk_artifact_created_by_actor_id_user_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["iam.organization.id"],
            name=op.f("fk_artifact_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["iam.user_account.id"],
            name=op.f("fk_artifact_owner_id_user_account"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("artifact_id", name=op.f("pk_artifact")),
        sa.UniqueConstraint("object_key", name=op.f("uq_artifact_object_key")),
        schema="content",
    )
    op.create_index(
        "uq_artifact_origin_upload_not_null",
        "artifact",
        ["origin_upload_id"],
        unique=True,
        schema="content",
        postgresql_where="origin_upload_id IS NOT NULL",
    )
    op.create_table(
        "idempotency_record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("key_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("key_hash_version", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("response_body_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("response_digest", sa.CHAR(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status = 'PROCESSING' AND resource_type IS NULL AND resource_id IS NULL AND response_code IS NULL AND response_body_json IS NULL AND response_digest IS NULL) OR (status = 'COMPLETED' AND resource_type IS NOT NULL AND resource_id IS NOT NULL AND response_code IS NOT NULL AND response_body_json IS NOT NULL AND response_digest IS NOT NULL)",
            name=op.f("ck_idempotency_record_status_result_shape"),
        ),
        sa.CheckConstraint(
            "key_digest ~ '^[0-9a-f]{64}$'", name=op.f("ck_idempotency_record_key_digest_lower_hex")
        ),
        sa.CheckConstraint(
            "request_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_idempotency_record_request_hash_lower_hex"),
        ),
        sa.CheckConstraint(
            "response_digest IS NULL OR response_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_idempotency_record_response_digest_lower_hex"),
        ),
        sa.CheckConstraint(
            "status IN ('PROCESSING','COMPLETED')",
            name=op.f("ck_idempotency_record_status_allowed"),
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_idempotency_record_expiry_after_creation")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["iam.user_account.id"],
            name=op.f("fk_idempotency_record_actor_id_user_account"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_record")),
        sa.UniqueConstraint(
            "scope",
            "actor_id",
            "key_digest",
            name=op.f("uq_idempotency_record_scope_actor_id_key_digest"),
        ),
        schema="integration",
    )
    op.create_table(
        "policy_snapshot",
        sa.Column("policy_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("policy_revision", sa.BigInteger(), nullable=False),
        sa.Column("policy_bundle_id", sa.String(length=128), nullable=False),
        sa.Column("policy_bundle_version", sa.String(length=64), nullable=False),
        sa.Column("policy_bundle_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("effective_scope_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("policy_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_scope_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_policy_snapshot_scope_digest_lower_hex"),
        ),
        sa.CheckConstraint(
            "policy_bundle_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_policy_snapshot_bundle_digest_lower_hex"),
        ),
        sa.CheckConstraint(
            "policy_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_policy_snapshot_policy_digest_lower_hex"),
        ),
        sa.CheckConstraint(
            "policy_revision >= 1", name=op.f("ck_policy_snapshot_policy_revision_positive")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["iam.user_account.id"],
            name=op.f("fk_policy_snapshot_actor_id_user_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["iam.organization.id"],
            name=op.f("fk_policy_snapshot_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("policy_snapshot_id", name=op.f("pk_policy_snapshot")),
        sa.UniqueConstraint(
            "organization_id",
            "actor_id",
            "policy_revision",
            "policy_digest",
            name=op.f("uq_policy_snapshot_organization_id_actor_id_policy_revision_policy_digest"),
        ),
        schema="policy",
    )
    op.create_table(
        "conversation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("conversation_memory_version", sa.BigInteger(), nullable=False),
        sa.Column("memory_policy", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "memory_policy IN ('OFF','CONVERSATION','USER_PRIVATE_ALLOWED')",
            name=op.f("ck_conversation_memory_policy_allowed"),
        ),
        sa.CheckConstraint(
            "conversation_memory_version >= 0",
            name=op.f("ck_conversation_memory_version_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["iam.organization.id"],
            name=op.f("fk_conversation_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["iam.user_account.id"],
            name=op.f("fk_conversation_owner_id_user_account"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation")),
        schema="workflow",
    )
    op.create_index(
        "ix_conversation_owner_updated",
        "conversation",
        ["owner_id", "updated_at", "id"],
        unique=False,
        schema="workflow",
    )
    op.create_table(
        "conversation_message",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("message_kind", sa.String(length=32), nullable=False),
        sa.Column("content_artifact_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("supersedes_id", sa.UUID(), nullable=True),
        sa.Column("content_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(message_kind IN ('USER_QUERY','USER_APPEND') AND role = 'USER') OR (message_kind = 'ASSISTANT_FINAL' AND role = 'ASSISTANT') OR (message_kind IN ('TASK_FAILED_NOTICE','TASK_CANCELLED_NOTICE','TASK_RERUN_NOTICE') AND role = 'SYSTEM_NOTICE')",
            name=op.f("ck_conversation_message_kind_role_match"),
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_conversation_message_content_hash_lower_hex"),
        ),
        sa.CheckConstraint(
            "message_kind NOT IN ('USER_QUERY','USER_APPEND','ASSISTANT_FINAL','TASK_FAILED_NOTICE','TASK_CANCELLED_NOTICE','TASK_RERUN_NOTICE') OR task_id IS NOT NULL",
            name=op.f("ck_conversation_message_task_kind_has_task"),
        ),
        sa.CheckConstraint(
            "state IN ('ACTIVE','SUPERSEDED','RETRACTED')",
            name=op.f("ck_conversation_message_state_allowed"),
        ),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_conversation_message_revision_positive")),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_conversation_message_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["content_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_conversation_message_content_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["workflow.conversation.id"],
            name=op.f("fk_conversation_message_conversation_id_conversation"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["workflow.conversation_message.id"],
            name=op.f("fk_conversation_message_supersedes_id_conversation_message"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["workflow.intelligent_task.id"],
            name=op.f("fk_conversation_message_task_id_intelligent_task"),
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_message")),
        sa.UniqueConstraint(
            "conversation_id",
            "sequence",
            "revision",
            name=op.f("uq_conversation_message_conversation_id_sequence_revision"),
        ),
        schema="workflow",
    )
    op.create_index(
        "uq_conversation_message_active_revision",
        "conversation_message",
        ["conversation_id", "sequence"],
        unique=True,
        schema="workflow",
        postgresql_where=sa.text("state = 'ACTIVE'"),
    )
    op.create_index(
        "uq_conversation_message_active_task_kind",
        "conversation_message",
        ["task_id", "message_kind"],
        unique=True,
        schema="workflow",
        postgresql_where=sa.text(
            "state = 'ACTIVE' AND message_kind IN ('USER_QUERY','ASSISTANT_FINAL')"
        ),
    )
    op.create_table(
        "intelligent_task",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("rerun_of_task_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("query_artifact_id", sa.UUID(), nullable=False),
        sa.Column("initial_input_id", sa.UUID(), nullable=False),
        sa.Column("current_input_id", sa.UUID(), nullable=False),
        sa.Column("authorization_ref_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="QUEUED", nullable=False),
        sa.Column("active_plan_version", sa.Integer(), nullable=True),
        sa.Column("temporal_workflow_id", sa.String(length=255), nullable=False),
        sa.Column("last_event_sequence", sa.BigInteger(), nullable=False),
        sa.Column("budget", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("budget_used", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result_artifact_id", sa.UUID(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(budget) = 'object'", name=op.f("ck_intelligent_task_budget_object")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(budget_used) = 'object'",
            name=op.f("ck_intelligent_task_budget_used_object"),
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED','PLANNING','RUNNING','REPLANNING','FINALIZING','WAITING_USER_INPUT','WAITING_APPROVAL','RETRY_WAIT','CANCEL_REQUESTED','COMPLETED','FAILED','CANCELLED')",
            name=op.f("ck_intelligent_task_status_allowed"),
        ),
        sa.CheckConstraint(
            "temporal_workflow_id = 'agent-task-v1-' || lower(id::text)",
            name=op.f("ck_intelligent_task_temporal_workflow_id_deterministic"),
        ),
        sa.CheckConstraint(
            "active_plan_version IS NULL OR active_plan_version >= 1",
            name=op.f("ck_intelligent_task_plan_positive"),
        ),
        sa.CheckConstraint(
            "deadline_at > created_at", name=op.f("ck_intelligent_task_deadline_after_creation")
        ),
        sa.CheckConstraint(
            "last_event_sequence >= 0", name=op.f("ck_intelligent_task_event_sequence_nonnegative")
        ),
        sa.CheckConstraint(
            "rerun_of_task_id IS NULL OR rerun_of_task_id <> id",
            name=op.f("ck_intelligent_task_rerun_not_self"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_intelligent_task_version_positive")),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["workflow.conversation.id"],
            name=op.f("fk_intelligent_task_conversation_id_conversation"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["current_input_id"],
            ["workflow.task_input_snapshot.input_id"],
            name=op.f("fk_intelligent_task_current_input_id_task_input_snapshot"),
            ondelete="RESTRICT",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["initial_input_id"],
            ["workflow.task_input_snapshot.input_id"],
            name=op.f("fk_intelligent_task_initial_input_id_task_input_snapshot"),
            ondelete="RESTRICT",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["iam.organization.id"],
            name=op.f("fk_intelligent_task_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["iam.user_account.id"],
            name=op.f("fk_intelligent_task_owner_id_user_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["query_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_intelligent_task_query_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rerun_of_task_id"],
            ["workflow.intelligent_task.id"],
            name=op.f("fk_intelligent_task_rerun_of_task_id_intelligent_task"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["result_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_intelligent_task_result_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intelligent_task")),
        sa.UniqueConstraint(
            "temporal_workflow_id", name=op.f("uq_intelligent_task_temporal_workflow_id")
        ),
        schema="workflow",
    )
    op.create_index(
        "ix_intelligent_task_conversation",
        "intelligent_task",
        ["conversation_id"],
        unique=False,
        schema="workflow",
    )
    op.create_index(
        "ix_intelligent_task_open_deadline",
        "intelligent_task",
        ["deadline_at", "id"],
        unique=False,
        schema="workflow",
        postgresql_where=sa.text("status NOT IN ('COMPLETED','FAILED','CANCELLED')"),
    )
    op.create_index(
        "ix_intelligent_task_owner_created",
        "intelligent_task",
        ["owner_id", "created_at", "id"],
        unique=False,
        schema="workflow",
    )
    op.create_index(
        "ix_intelligent_task_rerun",
        "intelligent_task",
        ["rerun_of_task_id"],
        unique=False,
        schema="workflow",
    )
    op.create_index(
        "ix_intelligent_task_status_created",
        "intelligent_task",
        ["status", "created_at"],
        unique=False,
        schema="workflow",
    )
    op.create_table(
        "task_attachment_binding",
        sa.Column("binding_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("introduced_by_message_id", sa.UUID(), nullable=False),
        sa.Column("source_sha256", sa.CHAR(length=64), nullable=False),
        sa.Column("preflight_run_id", sa.UUID(), nullable=False),
        sa.Column("detected_media_type", sa.String(length=128), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("task_terminal_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "source_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_task_attachment_binding_source_sha256_lower_hex"),
        ),
        sa.CheckConstraint(
            "state IN ('ACTIVE','EXPIRED','DELETED')",
            name=op.f("ck_task_attachment_binding_state_allowed"),
        ),
        sa.CheckConstraint(
            "ordinal BETWEEN 1 AND 20", name=op.f("ck_task_attachment_binding_ordinal_range")
        ),
        sa.CheckConstraint(
            "row_version >= 1", name=op.f("ck_task_attachment_binding_row_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_task_attachment_binding_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["introduced_by_message_id"],
            ["workflow.conversation_message.id"],
            name=op.f("fk_task_attachment_binding_introduced_by_message_id_conversation_message"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["iam.user_account.id"],
            name=op.f("fk_task_attachment_binding_owner_id_user_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["workflow.intelligent_task.id"],
            name=op.f("fk_task_attachment_binding_task_id_intelligent_task"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("binding_id", name=op.f("pk_task_attachment_binding")),
        sa.UniqueConstraint(
            "task_id", "artifact_id", name=op.f("uq_task_attachment_binding_task_id_artifact_id")
        ),
        sa.UniqueConstraint(
            "task_id", "ordinal", name=op.f("uq_task_attachment_binding_task_id_ordinal")
        ),
        schema="workflow",
    )
    op.create_table(
        "task_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("event_schema_version", sa.String(length=64), nullable=False),
        sa.Column("workflow_relevant", sa.Boolean(), nullable=False),
        sa.Column("business_ref_type", sa.String(length=64), nullable=True),
        sa.Column("business_ref_id", sa.UUID(), nullable=True),
        sa.Column("business_version", sa.BigInteger(), nullable=True),
        sa.Column("observation_projection_profile_version", sa.String(length=64), nullable=True),
        sa.Column("observation_expected_count", sa.Integer(), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_digest", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "payload_digest ~ '^[0-9a-f]{64}$'", name=op.f("ck_task_event_payload_digest_lower_hex")
        ),
        sa.CheckConstraint(
            "(business_ref_type IS NULL AND business_ref_id IS NULL AND business_version IS NULL) OR (business_ref_type IS NOT NULL AND business_ref_id IS NOT NULL AND business_version IS NOT NULL)",
            name=op.f("ck_task_event_business_ref_all_or_none"),
        ),
        sa.CheckConstraint(
            "NOT workflow_relevant OR (business_ref_type IS NOT NULL AND business_ref_id IS NOT NULL AND business_version IS NOT NULL)",
            name=op.f("ck_task_event_workflow_event_has_business_ref"),
        ),
        sa.CheckConstraint(
            "business_version IS NULL OR business_version >= 1",
            name=op.f("ck_task_event_business_version_positive"),
        ),
        sa.CheckConstraint(
            "observation_expected_count >= 0",
            name=op.f("ck_task_event_observation_count_nonnegative"),
        ),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_task_event_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["workflow.intelligent_task.id"],
            name=op.f("fk_task_event_task_id_intelligent_task"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("task_id", "sequence", name=op.f("pk_task_event")),
        sa.UniqueConstraint("id", name=op.f("uq_task_event_id")),
        schema="workflow",
    )
    op.create_index(
        "ix_task_event_workflow_sequence",
        "task_event",
        ["task_id", "workflow_relevant", "sequence"],
        unique=False,
        schema="workflow",
    )
    op.create_index(
        "uq_task_event_business_version",
        "task_event",
        ["task_id", "business_ref_type", "business_ref_id", "business_version"],
        unique=True,
        schema="workflow",
        postgresql_where=sa.text("business_ref_id IS NOT NULL"),
    )
    op.create_table(
        "task_input_snapshot",
        sa.Column("input_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("input_revision", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("message_artifact_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column(
            "attachment_binding_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("knowledge_scope_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("network_policy", sa.String(length=16), nullable=False),
        sa.Column("network_policy_source", sa.String(length=32), nullable=False),
        sa.Column("output_contract_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "selected_resource_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "task_constraint_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "policy_snapshot_ref_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("locale", sa.String(length=35), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("contract_version", sa.String(length=64), nullable=False),
        sa.Column("snapshot_digest", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "contract_version = 'task_input_snapshot_v1'",
            name=op.f("ck_task_input_snapshot_contract_version_v1"),
        ),
        sa.CheckConstraint(
            "network_policy IN ('DENY','ASK','ALLOW')",
            name=op.f("ck_task_input_snapshot_network_policy_allowed"),
        ),
        sa.CheckConstraint(
            "network_policy_source IN ('UI_FIELD','QUERY_SPAN','SYSTEM_DEFAULT')",
            name=op.f("ck_task_input_snapshot_network_policy_source_allowed"),
        ),
        sa.CheckConstraint(
            "snapshot_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_task_input_snapshot_snapshot_digest_lower_hex"),
        ),
        sa.CheckConstraint(
            "input_revision >= 1", name=op.f("ck_task_input_snapshot_input_revision_positive")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["iam.user_account.id"],
            name=op.f("fk_task_input_snapshot_actor_id_user_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["workflow.conversation.id"],
            name=op.f("fk_task_input_snapshot_conversation_id_conversation"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["message_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_task_input_snapshot_message_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["workflow.conversation_message.id"],
            name=op.f("fk_task_input_snapshot_message_id_conversation_message"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["iam.organization.id"],
            name=op.f("fk_task_input_snapshot_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["workflow.intelligent_task.id"],
            name=op.f("fk_task_input_snapshot_task_id_intelligent_task"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("input_id", name=op.f("pk_task_input_snapshot")),
        sa.UniqueConstraint(
            "task_id", "input_revision", name=op.f("uq_task_input_snapshot_task_id_input_revision")
        ),
        schema="workflow",
    )
    op.create_table(
        "outbox_message",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_version", sa.BigInteger(), nullable=False),
        sa.Column("destination", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("publish_status", sa.String(length=16), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("claimed_by", sa.String(length=128), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(publish_status = 'PUBLISHING' AND claimed_by IS NOT NULL AND claimed_at IS NOT NULL AND published_at IS NULL) OR (publish_status = 'PUBLISHED' AND published_at IS NOT NULL) OR (publish_status IN ('PENDING','DEAD') AND claimed_by IS NULL AND claimed_at IS NULL AND published_at IS NULL)",
            name=op.f("ck_outbox_message_publish_state_shape"),
        ),
        sa.CheckConstraint(
            "destination IN ('MQ','TEMPORAL_START','TEMPORAL_SIGNAL','TEMPORAL_CANCEL')",
            name=op.f("ck_outbox_message_destination_allowed"),
        ),
        sa.CheckConstraint(
            "payload_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_outbox_message_payload_digest_lower_hex"),
        ),
        sa.CheckConstraint(
            "publish_status IN ('PENDING','PUBLISHING','PUBLISHED','DEAD')",
            name=op.f("ck_outbox_message_publish_status_allowed"),
        ),
        sa.CheckConstraint(
            "aggregate_version >= 1", name=op.f("ck_outbox_message_aggregate_version_positive")
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_outbox_message_attempt_count_nonnegative")
        ),
        sa.CheckConstraint("row_version >= 1", name=op.f("ck_outbox_message_row_version_positive")),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["workflow.task_event.id"],
            name=op.f("fk_outbox_message_event_id_task_event"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_message")),
        sa.UniqueConstraint(
            "event_id", "destination", name=op.f("uq_outbox_message_event_id_destination")
        ),
        schema="integration",
    )
    op.create_index(
        "ix_outbox_claim",
        "outbox_message",
        ["publish_status", "available_at", "id"],
        unique=False,
        schema="integration",
    )
    op.create_table(
        "task_explicit_constraint",
        sa.Column("constraint_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("input_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("normalized_value", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_field", sa.String(length=128), nullable=True),
        sa.Column("source_span_start", sa.Integer(), nullable=True),
        sa.Column("source_span_end", sa.Integer(), nullable=True),
        sa.Column("polarity", sa.String(length=16), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("resolution_status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(source = 'UI_FIELD' AND source_field IS NOT NULL AND source_span_start IS NULL AND source_span_end IS NULL) OR (source = 'QUERY_SPAN' AND source_field IS NULL AND source_span_start >= 0 AND source_span_end > source_span_start) OR (source NOT IN ('UI_FIELD','QUERY_SPAN') AND source_span_start IS NULL AND source_span_end IS NULL)",
            name=op.f("ck_task_explicit_constraint_source_location_shape"),
        ),
        sa.CheckConstraint(
            "polarity IN ('REQUIRE','FORBID')",
            name=op.f("ck_task_explicit_constraint_polarity_allowed"),
        ),
        sa.CheckConstraint(
            "resolution_status IN ('EFFECTIVE','SHADOWED','CONFLICTED')",
            name=op.f("ck_task_explicit_constraint_resolution_status_allowed"),
        ),
        sa.CheckConstraint(
            "source IN ('POLICY','UI_FIELD','QUERY_SPAN','PRIOR_TASK','USER_PREFERENCE','SYSTEM_DEFAULT')",
            name=op.f("ck_task_explicit_constraint_source_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["input_id"],
            ["workflow.task_input_snapshot.input_id"],
            name=op.f("fk_task_explicit_constraint_input_id_task_input_snapshot"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["workflow.intelligent_task.id"],
            name=op.f("fk_task_explicit_constraint_task_id_intelligent_task"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("constraint_id", name=op.f("pk_task_explicit_constraint")),
        schema="workflow",
    )
    op.create_table(
        "task_intent_parse",
        sa.Column("parse_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("input_id", sa.UUID(), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("constraint_set_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("classification_schema_version", sa.String(length=64), nullable=False),
        sa.Column("classification_artifact_id", sa.UUID(), nullable=True),
        sa.Column("fixed_intent_candidate", sa.String(length=64), nullable=True),
        sa.Column("required_slots_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_slots_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ambiguity_flags_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_spans_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_profile_ref_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "constraint_set_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_task_intent_parse_constraint_digest_lower_hex"),
        ),
        sa.CheckConstraint(
            "status IN ('CONSTRAINT_CONFLICT','CLASSIFIED','UNMATCHED','INVALID_OUTPUT','DEGRADED_TO_SUPERVISOR')",
            name=op.f("ck_task_intent_parse_status_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["classification_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_task_intent_parse_classification_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["input_id"],
            ["workflow.task_input_snapshot.input_id"],
            name=op.f("fk_task_intent_parse_input_id_task_input_snapshot"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["workflow.intelligent_task.id"],
            name=op.f("fk_task_intent_parse_task_id_intelligent_task"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("parse_id", name=op.f("pk_task_intent_parse")),
        sa.UniqueConstraint(
            "task_id",
            "input_id",
            "parser_version",
            name=op.f("uq_task_intent_parse_task_id_input_id_parser_version"),
        ),
        schema="workflow",
    )
    op.create_table(
        "fixed_workflow_admission",
        sa.Column("admission_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("input_id", sa.UUID(), nullable=False),
        sa.Column("parse_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.String(length=128), nullable=False),
        sa.Column("profile_version", sa.String(length=64), nullable=False),
        sa.Column("profile_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("anchor_grammar_version", sa.String(length=64), nullable=False),
        sa.Column("anchor_grammar_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("normalization_profile", sa.String(length=128), nullable=False),
        sa.Column("slot_resolver_profile", sa.String(length=128), nullable=False),
        sa.Column("slot_resolver_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("language_alias_map_version", sa.String(length=64), nullable=False),
        sa.Column("language_alias_map_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("candidate", sa.String(length=64), nullable=True),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("check_results_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason_codes_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("anchor_matches_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("slot_resolution_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("workflow_id", sa.String(length=128), nullable=True),
        sa.Column("workflow_version", sa.String(length=64), nullable=True),
        sa.Column("output_contract_ref", sa.String(length=256), nullable=True),
        sa.Column("output_contract_digest", sa.CHAR(length=64), nullable=True),
        sa.Column("renderer_profile", sa.String(length=128), nullable=True),
        sa.Column("renderer_digest", sa.CHAR(length=64), nullable=True),
        sa.Column("classification_schema_version", sa.String(length=64), nullable=False),
        sa.Column("model_profile_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_profile_version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(decision = 'ADMIT_FIXED_WORKFLOW' AND candidate IS NOT NULL AND workflow_id IS NOT NULL AND workflow_version IS NOT NULL AND output_contract_ref IS NOT NULL AND output_contract_digest IS NOT NULL AND renderer_profile IS NOT NULL AND renderer_digest IS NOT NULL) OR (decision = 'SUPERVISOR' AND workflow_id IS NULL AND workflow_version IS NULL AND output_contract_ref IS NULL AND output_contract_digest IS NULL AND renderer_profile IS NULL AND renderer_digest IS NULL)",
            name=op.f("ck_fixed_workflow_admission_decision_branch_shape"),
        ),
        sa.CheckConstraint(
            "anchor_grammar_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_fixed_workflow_admission_grammar_digest_lower_hex"),
        ),
        sa.CheckConstraint(
            "decision IN ('ADMIT_FIXED_WORKFLOW','SUPERVISOR')",
            name=op.f("ck_fixed_workflow_admission_decision_allowed"),
        ),
        sa.CheckConstraint(
            "language_alias_map_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_fixed_workflow_admission_alias_digest_lower_hex"),
        ),
        sa.CheckConstraint(
            "profile_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_fixed_workflow_admission_profile_digest_lower_hex"),
        ),
        sa.CheckConstraint(
            "slot_resolver_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_fixed_workflow_admission_resolver_digest_lower_hex"),
        ),
        sa.ForeignKeyConstraint(
            ["input_id"],
            ["workflow.task_input_snapshot.input_id"],
            name=op.f("fk_fixed_workflow_admission_input_id_task_input_snapshot"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parse_id"],
            ["workflow.task_intent_parse.parse_id"],
            name=op.f("fk_fixed_workflow_admission_parse_id_task_intent_parse"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["workflow.intelligent_task.id"],
            name=op.f("fk_fixed_workflow_admission_task_id_intelligent_task"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("admission_id", name=op.f("pk_fixed_workflow_admission")),
        sa.UniqueConstraint(
            "task_id",
            "input_id",
            "parse_id",
            "profile_version",
            name=op.f("uq_fixed_workflow_admission_task_id_input_id_parse_id_profile_version"),
        ),
        schema="workflow",
    )
    # Circular Task/Input/Message relations must be added only after all three tables exist.
    op.create_foreign_key(
        op.f("fk_conversation_message_task_id_intelligent_task"),
        "conversation_message",
        "intelligent_task",
        ["task_id"],
        ["id"],
        source_schema="workflow",
        referent_schema="workflow",
        ondelete="RESTRICT",
    )
    for column_name in ("initial_input_id", "current_input_id"):
        op.create_foreign_key(
            op.f(f"fk_intelligent_task_{column_name}_task_input_snapshot"),
            "intelligent_task",
            "task_input_snapshot",
            [column_name],
            ["input_id"],
            source_schema="workflow",
            referent_schema="workflow",
            ondelete="RESTRICT",
            deferrable=True,
            initially="DEFERRED",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for constraint_name in (
        "fk_intelligent_task_current_input_id_task_input_snapshot",
        "fk_intelligent_task_initial_input_id_task_input_snapshot",
    ):
        op.drop_constraint(
            constraint_name,
            "intelligent_task",
            schema="workflow",
            type_="foreignkey",
        )
    op.drop_constraint(
        "fk_conversation_message_task_id_intelligent_task",
        "conversation_message",
        schema="workflow",
        type_="foreignkey",
    )
    op.drop_table("fixed_workflow_admission", schema="workflow")
    op.drop_table("task_intent_parse", schema="workflow")
    op.drop_table("task_explicit_constraint", schema="workflow")
    op.drop_index("ix_outbox_claim", table_name="outbox_message", schema="integration")
    op.drop_table("outbox_message", schema="integration")
    op.drop_table("task_input_snapshot", schema="workflow")
    op.drop_index(
        "uq_task_event_business_version",
        table_name="task_event",
        schema="workflow",
        postgresql_where=sa.text("business_ref_id IS NOT NULL"),
    )
    op.drop_index("ix_task_event_workflow_sequence", table_name="task_event", schema="workflow")
    op.drop_table("task_event", schema="workflow")
    op.drop_table("task_attachment_binding", schema="workflow")
    op.drop_index(
        "ix_intelligent_task_status_created", table_name="intelligent_task", schema="workflow"
    )
    op.drop_index("ix_intelligent_task_rerun", table_name="intelligent_task", schema="workflow")
    op.drop_index(
        "ix_intelligent_task_owner_created", table_name="intelligent_task", schema="workflow"
    )
    op.drop_index(
        "ix_intelligent_task_open_deadline",
        table_name="intelligent_task",
        schema="workflow",
        postgresql_where=sa.text("status NOT IN ('COMPLETED','FAILED','CANCELLED')"),
    )
    op.drop_index(
        "ix_intelligent_task_conversation", table_name="intelligent_task", schema="workflow"
    )
    op.drop_table("intelligent_task", schema="workflow")
    op.drop_index(
        "uq_conversation_message_active_task_kind",
        table_name="conversation_message",
        schema="workflow",
        postgresql_where=sa.text(
            "state = 'ACTIVE' AND message_kind IN ('USER_QUERY','ASSISTANT_FINAL')"
        ),
    )
    op.drop_index(
        "uq_conversation_message_active_revision",
        table_name="conversation_message",
        schema="workflow",
        postgresql_where=sa.text("state = 'ACTIVE'"),
    )
    op.drop_table("conversation_message", schema="workflow")
    op.drop_index("ix_conversation_owner_updated", table_name="conversation", schema="workflow")
    op.drop_table("conversation", schema="workflow")
    op.drop_table("policy_snapshot", schema="policy")
    op.drop_table("idempotency_record", schema="integration")
    op.drop_index(
        "uq_artifact_origin_upload_not_null",
        table_name="artifact",
        schema="content",
        postgresql_where="origin_upload_id IS NOT NULL",
    )
    op.drop_table("artifact", schema="content")
    op.drop_index("ix_user_account_status", table_name="user_account", schema="iam")
    op.drop_table("user_account", schema="iam")
    op.drop_table("organization", schema="iam")
    # ### end Alembic commands ###
    for schema in ("integration", "workflow", "policy", "content", "iam"):
        op.execute(sa.text(f'DROP SCHEMA IF EXISTS "{schema}"'))
