"""goal_plan_persistence

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-15 23:44:02.697279
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_goal_understanding",
        sa.Column("understanding_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("input_id", sa.UUID(), nullable=False),
        sa.Column("task_attempt_id", sa.UUID(), nullable=False),
        sa.Column("contract_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_profile", sa.String(length=64), nullable=False),
        sa.Column("prompt_profile_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("model_alias", sa.String(length=64), nullable=False),
        sa.Column("goal_context_artifact_id", sa.UUID(), nullable=False),
        sa.Column("context_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("raw_model_artifact_id", sa.UUID(), nullable=False),
        sa.Column("goal_artifact_id", sa.UUID(), nullable=False),
        sa.Column("understanding_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("gate_profile", sa.String(length=64), nullable=False),
        sa.Column("gate_profile_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("gate_artifact_id", sa.UUID(), nullable=False),
        sa.Column("gate_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("gate_outcome", sa.String(length=32), nullable=False),
        sa.Column("subgoal_count", sa.Integer(), nullable=False),
        sa.Column("criterion_count", sa.Integer(), nullable=False),
        sa.Column("assumption_count", sa.Integer(), nullable=False),
        sa.Column("blocking_issue_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "gate_outcome <> 'REQUEST_USER_INPUT' OR blocking_issue_count BETWEEN 1 AND 3",
            name=op.f("ck_task_goal_understanding_gate_blocking_issue_shape"),
        ),
        sa.CheckConstraint(
            "contract_version = 'supervisor_goal_understanding_v1'",
            name=op.f("ck_task_goal_understanding_contract_version_v1"),
        ),
        sa.CheckConstraint(
            "gate_outcome IN ('READY_TO_PLAN','REQUEST_USER_INPUT')",
            name=op.f("ck_task_goal_understanding_gate_outcome_allowed"),
        ),
        sa.CheckConstraint(
            "gate_profile = 'clarification_gate_v1'",
            name=op.f("ck_task_goal_understanding_gate_profile_v1"),
        ),
        sa.CheckConstraint(
            "model_alias = 'planning_strong'",
            name=op.f("ck_task_goal_understanding_model_alias_planning"),
        ),
        sa.CheckConstraint(
            "prompt_profile = 'supervisor-goal-understanding-v1'",
            name=op.f("ck_task_goal_understanding_prompt_profile_v1"),
        ),
        sa.CheckConstraint(
            "prompt_profile_digest ~ '^[0-9a-f]{64}$' AND context_digest ~ '^[0-9a-f]{64}$' AND understanding_digest ~ '^[0-9a-f]{64}$' AND gate_profile_digest ~ '^[0-9a-f]{64}$' AND gate_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_task_goal_understanding_digests_lower_hex"),
        ),
        sa.CheckConstraint(
            "assumption_count BETWEEN 0 AND 8",
            name=op.f("ck_task_goal_understanding_assumption_count_range"),
        ),
        sa.CheckConstraint(
            "blocking_issue_count BETWEEN 0 AND 3",
            name=op.f("ck_task_goal_understanding_blocking_issue_count_range"),
        ),
        sa.CheckConstraint(
            "criterion_count BETWEEN 1 AND 12",
            name=op.f("ck_task_goal_understanding_criterion_count_range"),
        ),
        sa.CheckConstraint(
            "subgoal_count BETWEEN 0 AND 8",
            name=op.f("ck_task_goal_understanding_subgoal_count_range"),
        ),
        sa.ForeignKeyConstraint(
            ["gate_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_task_goal_understanding_gate_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["goal_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_task_goal_understanding_goal_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["goal_context_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_task_goal_understanding_goal_context_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["input_id"],
            ["workflow.task_input_snapshot.input_id"],
            name=op.f("fk_task_goal_understanding_input_id_task_input_snapshot"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["raw_model_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_task_goal_understanding_raw_model_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["workflow.intelligent_task.id"],
            name=op.f("fk_task_goal_understanding_task_id_intelligent_task"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("understanding_id", name=op.f("pk_task_goal_understanding")),
        sa.UniqueConstraint(
            "task_id",
            "input_id",
            "task_attempt_id",
            name=op.f("uq_task_goal_understanding_task_id_input_id_task_attempt_id"),
        ),
        schema="workflow",
    )
    op.create_table(
        "task_plan_version",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("predecessor_version", sa.Integer(), nullable=True),
        sa.Column("input_id", sa.UUID(), nullable=False),
        sa.Column("task_attempt_id", sa.UUID(), nullable=False),
        sa.Column("goal_understanding_id", sa.UUID(), nullable=False),
        sa.Column("planning_context_artifact_id", sa.UUID(), nullable=False),
        sa.Column("capability_planning_view_artifact_id", sa.UUID(), nullable=False),
        sa.Column("raw_model_artifact_id", sa.UUID(), nullable=False),
        sa.Column("validated_draft_artifact_id", sa.UUID(), nullable=False),
        sa.Column("validation_artifact_id", sa.UUID(), nullable=False),
        sa.Column("compiled_plan_artifact_id", sa.UUID(), nullable=False),
        sa.Column("compiled_plan_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("revision_reason", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by_agent_instance_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'ACTIVE' AND activated_at IS NOT NULL AND completed_at IS NULL) OR (status = 'SUPERSEDED' AND activated_at IS NOT NULL AND completed_at IS NOT NULL) OR (status = 'COMPLETED' AND activated_at IS NOT NULL AND completed_at IS NOT NULL) OR (status = 'ABANDONED' AND completed_at IS NOT NULL)",
            name=op.f("ck_task_plan_version_status_time_shape"),
        ),
        sa.CheckConstraint(
            "compiled_plan_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_task_plan_version_digest_lower_hex"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','SUPERSEDED','COMPLETED','ABANDONED')",
            name=op.f("ck_task_plan_version_status_allowed"),
        ),
        sa.CheckConstraint(
            "plan_version >= 1", name=op.f("ck_task_plan_version_plan_version_positive")
        ),
        sa.CheckConstraint(
            "predecessor_version IS NULL OR (predecessor_version >= 1 AND predecessor_version < plan_version)",
            name=op.f("ck_task_plan_version_predecessor_before_plan"),
        ),
        sa.ForeignKeyConstraint(
            ["capability_planning_view_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_task_plan_version_capability_planning_view_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["compiled_plan_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_task_plan_version_compiled_plan_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["goal_understanding_id"],
            ["workflow.task_goal_understanding.understanding_id"],
            name=op.f("fk_task_plan_version_goal_understanding_id_task_goal_understanding"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["input_id"],
            ["workflow.task_input_snapshot.input_id"],
            name=op.f("fk_task_plan_version_input_id_task_input_snapshot"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["planning_context_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_task_plan_version_planning_context_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["raw_model_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_task_plan_version_raw_model_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["workflow.intelligent_task.id"],
            name=op.f("fk_task_plan_version_task_id_intelligent_task"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["validated_draft_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_task_plan_version_validated_draft_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["validation_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_task_plan_version_validation_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("task_id", "plan_version", name=op.f("pk_task_plan_version")),
        schema="workflow",
    )
    op.create_index(
        "uq_task_plan_version_active",
        "task_plan_version",
        ["task_id"],
        unique=True,
        schema="workflow",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "task_compiled_criterion",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("criterion_id", sa.UUID(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requirement_level", sa.String(length=16), nullable=False),
        sa.Column("completion_role", sa.String(length=32), nullable=False),
        sa.Column("protected", sa.Boolean(), nullable=False),
        sa.Column("evaluation_mode", sa.String(length=40), nullable=False),
        sa.Column("predicate", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("applicability", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evaluator_profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("digest", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completion_role <> 'CORE_DELIVERABLE' OR requirement_level = 'REQUIRED'",
            name=op.f("ck_task_compiled_criterion_core_deliverable_required"),
        ),
        sa.CheckConstraint(
            "completion_role IN ('CORE_DELIVERABLE','REQUIRED_AUXILIARY','SUPPORTING')",
            name=op.f("ck_task_compiled_criterion_completion_role_allowed"),
        ),
        sa.CheckConstraint(
            "digest ~ '^[0-9a-f]{64}$'", name=op.f("ck_task_compiled_criterion_digest_lower_hex")
        ),
        sa.CheckConstraint(
            "evaluation_mode IN ('DETERMINISTIC','EVIDENCE_GROUNDED_SEMANTIC')",
            name=op.f("ck_task_compiled_criterion_evaluation_mode_allowed"),
        ),
        sa.CheckConstraint(
            "requirement_level IN ('REQUIRED','SUPPORTING')",
            name=op.f("ck_task_compiled_criterion_requirement_level_allowed"),
        ),
        sa.CheckConstraint(
            "source_kind IN ('USER','OUTPUT_CONTRACT','POLICY','GOAL','PLAN')",
            name=op.f("ck_task_compiled_criterion_source_kind_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "plan_version"],
            ["workflow.task_plan_version.task_id", "workflow.task_plan_version.plan_version"],
            name=op.f("fk_task_compiled_criterion_task_id_plan_version_task_plan_version"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "task_id", "plan_version", "criterion_id", name=op.f("pk_task_compiled_criterion")
        ),
        schema="workflow",
    )
    op.create_table(
        "task_plan_hypothesis",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("hypothesis_id", sa.UUID(), nullable=False),
        sa.Column("source_local_id", sa.String(length=64), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("initial_status", sa.String(length=16), nullable=False),
        sa.Column("hypothesis_digest", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "hypothesis_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_task_plan_hypothesis_digest_lower_hex"),
        ),
        sa.CheckConstraint(
            "initial_status = 'OPEN'", name=op.f("ck_task_plan_hypothesis_initial_status_open")
        ),
        sa.CheckConstraint(
            "source_local_id ~ '^[a-z][a-z0-9_-]{0,63}$'",
            name=op.f("ck_task_plan_hypothesis_source_local_id_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "plan_version"],
            ["workflow.task_plan_version.task_id", "workflow.task_plan_version.plan_version"],
            name=op.f("fk_task_plan_hypothesis_task_id_plan_version_task_plan_version"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "task_id", "plan_version", "hypothesis_id", name=op.f("pk_task_plan_hypothesis")
        ),
        sa.UniqueConstraint(
            "task_id",
            "plan_version",
            "source_local_id",
            name=op.f("uq_task_plan_hypothesis_task_id_plan_version_source_local_id"),
        ),
        schema="workflow",
    )
    op.create_table(
        "task_plan_item_definition",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("plan_item_id", sa.UUID(), nullable=False),
        sa.Column("source_local_id", sa.String(length=64), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("executor_requirement", sa.String(length=32), nullable=False),
        sa.Column(
            "capability_requirements_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "candidate_capability_refs_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "input_artifact_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "output_schema_ref_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "depends_on_item_ids_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("iteration_policy_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("initial_state", sa.String(length=16), nullable=False),
        sa.Column("definition_digest", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "definition_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_task_plan_item_definition_digest_lower_hex"),
        ),
        sa.CheckConstraint(
            "executor_requirement IN ('SUPERVISOR','SPECIALIST','DYNAMIC_ALLOWED')",
            name=op.f("ck_task_plan_item_definition_executor_requirement_allowed"),
        ),
        sa.CheckConstraint(
            "initial_state IN ('OPEN','READY')",
            name=op.f("ck_task_plan_item_definition_initial_state_allowed"),
        ),
        sa.CheckConstraint(
            "source_local_id ~ '^[a-z][a-z0-9_-]{0,63}$'",
            name=op.f("ck_task_plan_item_definition_source_local_id_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "plan_version"],
            ["workflow.task_plan_version.task_id", "workflow.task_plan_version.plan_version"],
            name=op.f("fk_task_plan_item_definition_task_id_plan_version_task_plan_version"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "task_id", "plan_version", "plan_item_id", name=op.f("pk_task_plan_item_definition")
        ),
        sa.UniqueConstraint(
            "task_id",
            "plan_version",
            "source_local_id",
            name=op.f("uq_task_plan_item_definition_task_id_plan_version_source_local_id"),
        ),
        schema="workflow",
    )
    op.create_table(
        "plan_item_runtime",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("plan_item_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("current_iteration", sa.Integer(), nullable=False),
        sa.Column("active_task_attempt_id", sa.UUID(), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status IN ('OPEN','READY','BLOCKED') AND completed_at IS NULL) OR (status = 'RUNNING' AND started_at IS NOT NULL AND completed_at IS NULL) OR (status IN ('COMPLETED','ABANDONED') AND completed_at IS NOT NULL)",
            name=op.f("ck_plan_item_runtime_status_time_shape"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','READY','RUNNING','BLOCKED','COMPLETED','ABANDONED')",
            name=op.f("ck_plan_item_runtime_status_allowed"),
        ),
        sa.CheckConstraint(
            "current_iteration BETWEEN 0 AND 3", name=op.f("ck_plan_item_runtime_iteration_range")
        ),
        sa.CheckConstraint(
            "row_version >= 1", name=op.f("ck_plan_item_runtime_row_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "plan_version", "plan_item_id"],
            [
                "workflow.task_plan_item_definition.task_id",
                "workflow.task_plan_item_definition.plan_version",
                "workflow.task_plan_item_definition.plan_item_id",
            ],
            name=op.f(
                "fk_plan_item_runtime_task_id_plan_version_plan_item_id_task_plan_item_definition"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "task_id", "plan_version", "plan_item_id", name=op.f("pk_plan_item_runtime")
        ),
        schema="workflow",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plan_item_runtime", schema="workflow")
    op.drop_table("task_plan_item_definition", schema="workflow")
    op.drop_table("task_plan_hypothesis", schema="workflow")
    op.drop_table("task_compiled_criterion", schema="workflow")
    op.drop_index(
        "uq_task_plan_version_active",
        table_name="task_plan_version",
        schema="workflow",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("task_plan_version", schema="workflow")
    op.drop_table("task_goal_understanding", schema="workflow")
    # ### end Alembic commands ###
