"""attempt_runtime_dependencies

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-16 12:13:34.915361
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 0002允许尚无Attempt表时写入Goal/Plan裸UUID。无法从这些UUID安全重建
    # Agent/Context/Attempt事实；拒绝迁移比伪造运行历史或在加FK时隐式失败安全。
    op.execute(
        sa.text(
            "DO $$ BEGIN IF EXISTS (SELECT 1 FROM workflow.task_goal_understanding) "
            "OR EXISTS (SELECT 1 FROM workflow.task_plan_version) THEN "
            "RAISE EXCEPTION 'ATTEMPT_RUNTIME_UPGRADE_LEGACY_GOAL_PLAN_REQUIRES_RECONCILIATION'; "
            "END IF; END $$"
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_instance",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("parent_agent_instance_id", sa.UUID(), nullable=True),
        sa.Column("manifest_id", sa.String(length=128), nullable=False),
        sa.Column("manifest_version", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("delegated_scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_reason", sa.Text(), nullable=False),
        sa.Column("created_reason_hash", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "created_reason_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_agent_instance_created_reason_hash_lower_hex"),
        ),
        sa.CheckConstraint(
            "kind <> 'EPHEMERAL' OR (parent_agent_instance_id IS NOT NULL AND expires_at IS NOT NULL)",
            name=op.f("ck_agent_instance_ephemeral_requires_parent_and_expiry"),
        ),
        sa.CheckConstraint(
            "kind IN ('SUPERVISOR','BUILT_IN','EPHEMERAL')",
            name=op.f("ck_agent_instance_kind_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('CREATED','ACTIVE','SUSPENDED','REVOKED','EXPIRED','COMPLETED')",
            name=op.f("ck_agent_instance_status_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_agent_instance_id"],
            ["workflow.agent_instance.id"],
            name=op.f("fk_agent_instance_parent_agent_instance_id_agent_instance"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["workflow.intelligent_task.id"],
            name=op.f("fk_agent_instance_task_id_intelligent_task"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_instance")),
        schema="workflow",
    )
    op.create_index(
        "uq_agent_instance_reuse_key",
        "agent_instance",
        [
            "task_id",
            "parent_agent_instance_id",
            "manifest_id",
            "manifest_version",
            "created_reason_hash",
        ],
        unique=True,
        schema="workflow",
        postgresql_where=sa.text("parent_agent_instance_id IS NOT NULL"),
    )
    op.create_table(
        "context_pack",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("action_attempt_id", sa.UUID(), nullable=True),
        sa.Column("created_by_attempt_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("authorization_ref_id", sa.UUID(), nullable=True),
        sa.Column("authorization_version", sa.BigInteger(), nullable=True),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("context_policy_version", sa.String(length=64), nullable=False),
        sa.Column("conversation_memory_version", sa.BigInteger(), nullable=False),
        sa.Column("user_private_memory_version", sa.BigInteger(), nullable=False),
        sa.Column("task_memory_version", sa.BigInteger(), nullable=False),
        sa.Column("runtime_version", sa.String(length=64), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=True),
        sa.Column("agent_manifest_version", sa.String(length=64), nullable=False),
        sa.Column("model_revision", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("tool_schema_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_schema_id", sa.String(length=128), nullable=True),
        sa.Column("output_schema_version", sa.String(length=64), nullable=True),
        sa.Column("tokenizer_revision", sa.String(length=128), nullable=False),
        sa.Column("chat_template_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("max_context", sa.Integer(), nullable=False),
        sa.Column("reserved_output", sa.Integer(), nullable=False),
        sa.Column("protocol_overhead", sa.Integer(), nullable=False),
        sa.Column("safety_margin", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("body_artifact_id", sa.UUID(), nullable=False),
        sa.Column("pack_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("input_digest", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "chat_template_hash ~ '^[0-9a-f]{64}$' AND pack_hash ~ '^[0-9a-f]{64}$' AND input_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_context_pack_digests_lower_hex"),
        ),
        sa.CheckConstraint(
            "state IN ('ASSEMBLING','READY','CONSUMED','FAILED','INVALIDATED_BEFORE_USE')",
            name=op.f("ck_context_pack_state_allowed"),
        ),
        sa.CheckConstraint(
            "conversation_memory_version >= 0 AND user_private_memory_version >= 0 AND task_memory_version >= 0",
            name=op.f("ck_context_pack_memory_versions_nonnegative"),
        ),
        sa.CheckConstraint(
            "max_context >= 0 AND reserved_output >= 0 AND protocol_overhead >= 0 AND safety_margin >= 0 AND input_tokens >= 0",
            name=op.f("ck_context_pack_budgets_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["iam.user_account.id"],
            name=op.f("fk_context_pack_actor_id_user_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["body_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_context_pack_body_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["workflow.conversation.id"],
            name=op.f("fk_context_pack_conversation_id_conversation"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["workflow.intelligent_task.id"],
            name=op.f("fk_context_pack_task_id_intelligent_task"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_context_pack")),
        sa.UniqueConstraint(
            "task_id",
            "action_attempt_id",
            "input_digest",
            "context_policy_version",
            name=op.f(
                "uq_context_pack_task_id_action_attempt_id_input_digest_context_policy_version"
            ),
            postgresql_nulls_not_distinct=True,
        ),
        schema="workflow",
    )
    op.create_table(
        "context_pack_item",
        sa.Column("context_pack_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("item_type", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_version", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("rank_score", sa.Float(), nullable=False),
        sa.Column("compression_level", sa.Integer(), nullable=False),
        sa.Column("selection_reason", sa.String(length=256), nullable=False),
        sa.Column("trust", sa.String(length=24), nullable=False),
        sa.Column("bucket", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_context_pack_item_content_hash_lower_hex"),
        ),
        sa.CheckConstraint(
            "compression_level >= 0",
            name=op.f("ck_context_pack_item_compression_level_nonnegative"),
        ),
        sa.CheckConstraint("position >= 1", name=op.f("ck_context_pack_item_position_positive")),
        sa.CheckConstraint(
            "token_count >= 0", name=op.f("ck_context_pack_item_token_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["context_pack_id"],
            ["workflow.context_pack.id"],
            name=op.f("fk_context_pack_item_context_pack_id_context_pack"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("context_pack_id", "position", name=op.f("pk_context_pack_item")),
        schema="workflow",
    )
    op.create_index(
        "ix_context_pack_item_source",
        "context_pack_item",
        ["source_type", "source_id"],
        unique=False,
        schema="workflow",
    )
    op.create_table(
        "task_attempt",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("input_id", sa.UUID(), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=True),
        sa.Column("plan_item_id", sa.UUID(), nullable=True),
        sa.Column("action_run_group_id", sa.UUID(), nullable=True),
        sa.Column("attempt_kind", sa.String(length=24), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("agent_instance_id", sa.UUID(), nullable=False),
        sa.Column("agent_registration_key", sa.String(length=64), nullable=False),
        sa.Column("manifest_id", sa.String(length=128), nullable=False),
        sa.Column("manifest_version", sa.String(length=64), nullable=False),
        sa.Column("manifest_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("context_pack_id", sa.UUID(), nullable=False),
        sa.Column("context_pack_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("grant_snapshot_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("capability_binding_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("capability_binding_snapshot_digest", sa.CHAR(length=64), nullable=True),
        sa.Column("budget_reservation_id", sa.UUID(), nullable=True),
        sa.Column("reservation_version", sa.Integer(), nullable=True),
        sa.Column("input_schema_version", sa.String(length=64), nullable=False),
        sa.Column("input_digest", sa.CHAR(length=64), nullable=False),
        sa.Column("pydantic_run_id", sa.String(length=128), nullable=False),
        sa.Column("resumes_task_attempt_id", sa.UUID(), nullable=True),
        sa.Column("temporal_child_workflow_id", sa.String(length=255), nullable=False),
        sa.Column("temporal_child_run_id", sa.UUID(), nullable=True),
        sa.Column("worker_id", sa.String(length=128), nullable=True),
        sa.Column("lease_generation", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("result_kind", sa.String(length=64), nullable=True),
        sa.Column("result_schema_version", sa.String(length=64), nullable=True),
        sa.Column("result_digest", sa.CHAR(length=64), nullable=True),
        sa.Column("suspension_kind", sa.String(length=24), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("failure_class", sa.String(length=32), nullable=True),
        sa.Column("diagnostic_artifact_id", sa.UUID(), nullable=True),
        sa.Column("external_effect_state", sa.String(length=24), nullable=False),
        sa.Column("replan_admission_id", sa.UUID(), nullable=True),
        sa.Column("replan_event_high_watermark", sa.BigInteger(), nullable=True),
        sa.Column("replan_context_artifact_id", sa.UUID(), nullable=True),
        sa.Column("execution_snapshot_artifact_id", sa.UUID(), nullable=True),
        sa.Column("final_synthesis_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("final_synthesis_snapshot_digest", sa.CHAR(length=64), nullable=True),
        sa.Column("runtime_decision_id", sa.UUID(), nullable=True),
        sa.Column("current_work_version", sa.BigInteger(), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(attempt_kind = 'ACTION' AND plan_item_id IS NOT NULL AND action_run_group_id IS NOT NULL) OR (attempt_kind <> 'ACTION' AND plan_item_id IS NULL AND action_run_group_id IS NULL)",
            name=op.f("ck_task_attempt_action_branch_shape"),
        ),
        sa.CheckConstraint(
            "(attempt_kind = 'FINAL_SYNTHESIS' AND final_synthesis_snapshot_id IS NOT NULL AND final_synthesis_snapshot_digest IS NOT NULL AND runtime_decision_id IS NOT NULL AND current_work_version IS NOT NULL) OR (attempt_kind <> 'FINAL_SYNTHESIS' AND final_synthesis_snapshot_id IS NULL AND final_synthesis_snapshot_digest IS NULL AND runtime_decision_id IS NULL AND current_work_version IS NULL)",
            name=op.f("ck_task_attempt_final_branch_shape"),
        ),
        sa.CheckConstraint(
            "(attempt_kind = 'GOAL_UNDERSTANDING' AND plan_version IS NULL) OR (attempt_kind <> 'GOAL_UNDERSTANDING' AND plan_version IS NOT NULL)",
            name=op.f("ck_task_attempt_plan_version_shape"),
        ),
        sa.CheckConstraint(
            "(attempt_kind = 'REPLAN' AND replan_admission_id IS NOT NULL AND replan_event_high_watermark IS NOT NULL AND replan_context_artifact_id IS NOT NULL AND execution_snapshot_artifact_id IS NOT NULL) OR (attempt_kind <> 'REPLAN' AND replan_admission_id IS NULL AND replan_event_high_watermark IS NULL AND replan_context_artifact_id IS NULL AND execution_snapshot_artifact_id IS NULL)",
            name=op.f("ck_task_attempt_replan_branch_shape"),
        ),
        sa.CheckConstraint(
            "(result_digest IS NULL OR result_digest ~ '^[0-9a-f]{64}$') AND (capability_binding_snapshot_digest IS NULL OR capability_binding_snapshot_digest ~ '^[0-9a-f]{64}$') AND (final_synthesis_snapshot_digest IS NULL OR final_synthesis_snapshot_digest ~ '^[0-9a-f]{64}$')",
            name=op.f("ck_task_attempt_nullable_digests_lower_hex"),
        ),
        sa.CheckConstraint(
            "agent_registration_key ~ '^[a-z][a-z0-9-]{0,63}$'",
            name=op.f("ck_task_attempt_agent_registration_key_shape"),
        ),
        sa.CheckConstraint(
            "attempt_kind IN ('GOAL_UNDERSTANDING','PLAN','REPLAN','ACTION','FINAL_SYNTHESIS')",
            name=op.f("ck_task_attempt_attempt_kind_allowed"),
        ),
        sa.CheckConstraint(
            "external_effect_state IN ('NO_EFFECT','EFFECT_CONFIRMED','OUTCOME_UNKNOWN','RECONCILING')",
            name=op.f("ck_task_attempt_external_effect_state_allowed"),
        ),
        sa.CheckConstraint(
            "failure_class IS NULL OR failure_class IN ('BUSINESS','DEPENDENCY','CONTRACT','POLICY','BUDGET','RESOURCE','EXTERNAL_EFFECT')",
            name=op.f("ck_task_attempt_failure_class_allowed"),
        ),
        sa.CheckConstraint(
            "manifest_digest ~ '^[0-9a-f]{64}$' AND context_pack_hash ~ '^[0-9a-f]{64}$' AND grant_snapshot_digest ~ '^[0-9a-f]{64}$' AND input_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_task_attempt_digests_lower_hex"),
        ),
        sa.CheckConstraint(
            "status IN ('CREATED','RUNNING','SUSPENDED','COMPLETED','FAILED','CANCELLED')",
            name=op.f("ck_task_attempt_status_allowed"),
        ),
        sa.CheckConstraint(
            "suspension_kind IS NULL OR suspension_kind IN ('APPROVAL','USER_INPUT','EXTERNAL_RESULT','MIXED')",
            name=op.f("ck_task_attempt_suspension_kind_allowed"),
        ),
        sa.CheckConstraint(
            "temporal_child_workflow_id = 'agent-attempt-v1-' || lower(task_id::text) || '-' || lower(id::text)",
            name=op.f("ck_task_attempt_child_workflow_id_deterministic"),
        ),
        sa.CheckConstraint("attempt_no >= 1", name=op.f("ck_task_attempt_attempt_no_positive")),
        sa.CheckConstraint(
            "lease_generation >= 0", name=op.f("ck_task_attempt_lease_generation_nonnegative")
        ),
        sa.CheckConstraint(
            "reservation_version IS NULL OR reservation_version >= 1",
            name=op.f("ck_task_attempt_reservation_version_positive"),
        ),
        sa.CheckConstraint("row_version >= 1", name=op.f("ck_task_attempt_row_version_positive")),
        sa.ForeignKeyConstraint(
            ["agent_instance_id"],
            ["workflow.agent_instance.id"],
            name=op.f("fk_task_attempt_agent_instance_id_agent_instance"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["context_pack_id"],
            ["workflow.context_pack.id"],
            name=op.f("fk_task_attempt_context_pack_id_context_pack"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["workflow.conversation.id"],
            name=op.f("fk_task_attempt_conversation_id_conversation"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["diagnostic_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_task_attempt_diagnostic_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["execution_snapshot_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_task_attempt_execution_snapshot_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["input_id"],
            ["workflow.task_input_snapshot.input_id"],
            name=op.f("fk_task_attempt_input_id_task_input_snapshot"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["replan_context_artifact_id"],
            ["content.artifact.artifact_id"],
            name=op.f("fk_task_attempt_replan_context_artifact_id_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resumes_task_attempt_id"],
            ["workflow.task_attempt.id"],
            name=op.f("fk_task_attempt_resumes_task_attempt_id_task_attempt"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["workflow.intelligent_task.id"],
            name=op.f("fk_task_attempt_task_id_intelligent_task"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_attempt")),
        sa.UniqueConstraint("pydantic_run_id", name=op.f("uq_task_attempt_pydantic_run_id")),
        sa.UniqueConstraint(
            "temporal_child_workflow_id", name=op.f("uq_task_attempt_temporal_child_workflow_id")
        ),
        schema="workflow",
    )
    op.create_index(
        "uq_task_attempt_action_group_attempt_no",
        "task_attempt",
        ["action_run_group_id", "attempt_no"],
        unique=True,
        schema="workflow",
        postgresql_where=sa.text("attempt_kind = 'ACTION'"),
    )
    op.create_index(
        "uq_task_attempt_task_kind_attempt_no",
        "task_attempt",
        ["task_id", "attempt_kind", "attempt_no"],
        unique=True,
        schema="workflow",
        postgresql_where=sa.text("attempt_kind <> 'ACTION'"),
    )
    op.create_foreign_key(
        op.f("fk_context_pack_created_by_attempt_id_task_attempt"),
        "context_pack",
        "task_attempt",
        ["created_by_attempt_id"],
        ["id"],
        source_schema="workflow",
        referent_schema="workflow",
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_plan_item_runtime_active_task_attempt_id_task_attempt"),
        "plan_item_runtime",
        "task_attempt",
        ["active_task_attempt_id"],
        ["id"],
        source_schema="workflow",
        referent_schema="workflow",
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_task_goal_understanding_task_attempt_id_task_attempt"),
        "task_goal_understanding",
        "task_attempt",
        ["task_attempt_id"],
        ["id"],
        source_schema="workflow",
        referent_schema="workflow",
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_task_plan_version_created_by_agent_instance_id_agent_instance"),
        "task_plan_version",
        "agent_instance",
        ["created_by_agent_instance_id"],
        ["id"],
        source_schema="workflow",
        referent_schema="workflow",
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_task_plan_version_task_attempt_id_task_attempt"),
        "task_plan_version",
        "task_attempt",
        ["task_attempt_id"],
        ["id"],
        source_schema="workflow",
        referent_schema="workflow",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # 降级会移除Attempt/Agent/Context表；只允许这些表仍为空时回退。
    # 有数据时必须恢复迁移前备份，不能留下指向已删除Attempt的Goal/Plan裸UUID。
    op.execute(
        sa.text(
            "DO $$ BEGIN IF EXISTS (SELECT 1 FROM workflow.task_attempt) "
            "OR EXISTS (SELECT 1 FROM workflow.agent_instance) "
            "OR EXISTS (SELECT 1 FROM workflow.context_pack) "
            "OR EXISTS (SELECT 1 FROM workflow.context_pack_item) THEN "
            "RAISE EXCEPTION 'ATTEMPT_RUNTIME_DOWNGRADE_REQUIRES_BACKUP_RESTORE'; "
            "END IF; END $$"
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_task_plan_version_task_attempt_id_task_attempt"),
        "task_plan_version",
        schema="workflow",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_task_plan_version_created_by_agent_instance_id_agent_instance"),
        "task_plan_version",
        schema="workflow",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_context_pack_created_by_attempt_id_task_attempt"),
        "context_pack",
        schema="workflow",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_task_goal_understanding_task_attempt_id_task_attempt"),
        "task_goal_understanding",
        schema="workflow",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_plan_item_runtime_active_task_attempt_id_task_attempt"),
        "plan_item_runtime",
        schema="workflow",
        type_="foreignkey",
    )
    op.drop_index(
        "uq_task_attempt_task_kind_attempt_no",
        table_name="task_attempt",
        schema="workflow",
        postgresql_where=sa.text("attempt_kind <> 'ACTION'"),
    )
    op.drop_index(
        "uq_task_attempt_action_group_attempt_no",
        table_name="task_attempt",
        schema="workflow",
        postgresql_where=sa.text("attempt_kind = 'ACTION'"),
    )
    op.drop_table("task_attempt", schema="workflow")
    op.drop_index("ix_context_pack_item_source", table_name="context_pack_item", schema="workflow")
    op.drop_table("context_pack_item", schema="workflow")
    op.drop_table("context_pack", schema="workflow")
    op.drop_index(
        "uq_agent_instance_reuse_key",
        table_name="agent_instance",
        schema="workflow",
        postgresql_where=sa.text("parent_agent_instance_id IS NOT NULL"),
    )
    op.drop_table("agent_instance", schema="workflow")
    # ### end Alembic commands ###
